---
- name: Create Systemd Service for CWTV Jitsi Teregram bot
  become: true
  ansible.builtin.template:
    src: 'templates/cwtv_telegram_bot.service.j2'
    dest: '/etc/systemd/system/cwtv_telegram_bot.service'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Make sure services are started
  become: true
  ansible.builtin.systemd_service:
    name: 'cwtv_telegram_bot.service'
    state: 'started'
    daemon_reload: true
    enabled: true
