---
- name: Make sure service is restarted
  listen: 'systemctl restart cwtv_telegram_bot.service'
  become: true
  ansible.builtin.systemd_service:
    name: 'cwtv_telegram_bot.service'
    state: 'started'
    daemon_reload: true
    enabled: true
